### ISSUE TITLE
Uncaught Error: Cannot find module 'atom-package-deps'

### ISSUE THREAD

**Issue by king889** [AtomLinter/atom-minimap-linter#78]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [minimap-linter](https://github.com/AtomLinter/atom-minimap-linter) package 2.2.1

### Stack Trace

Uncaught Error: Cannot find module 'atom-package-deps'

```
At internal/modules/cjs/loader.js:586

Error: Cannot find module 'atom-package-deps'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.45.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:146745)
    at installMinimapLinterDeps (/packages/atom-minimap-linter-master/lib/minimap-linter.js:17:9)
```

### Commands

```
```

### Non-Core Packages

```
minimap-linter 2.2.1 
script 3.25.0 
simplified-chinese-menu 5.3.5 
linter-pylama 0.10.1 
linter-python 3.1.2 
linter-python-pep8 0.2.0 
simplified-chinese-menu 5.3.5 
```

**Comment by Arcanemagus** [comment]
Try reinstalling the package, you are missing one of the dependencies that should have been installed with it.
